In [1]:
import os

In [2]:
os.getcwd()

'c:\\Users\\larry\\Desktop\\Geoguessr ML Proj\\Geolocation-Project'

In [3]:
os.chdir('c:\\Users\\larry\\Desktop\\Geoguessr ML Proj\\Geolocation-Project\\reverse_geocode3')

In [4]:
import data_loader
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from shapely.ops import nearest_points
from unidecode import unidecode

In [6]:
df, _ = data_loader.load_cities_and_build_kdtree_from_geonames()
len(df)

Loading city data from GeoNames cities500.txt...
Reading natural_earth_data/cities500.txt ...
Loaded 215735 entries from GeoNames.

--- Loading Admin Name Mappings ---
Loading Admin1 names from natural_earth_data/admin1CodesASCII.txt...
Loaded 3893 Admin1 name mappings.
Loading Admin2 names from natural_earth_data/admin2Codes.txt...
Loaded 47356 Admin2 name mappings.

--- Mapping Admin Codes to Names ---
Admin1 names mapped.
Admin2 names mapped.
Converting GeoNames data to GeoDataFrame...
Building KDTree for GeoNames cities...
KDTree built successfully.

215735

In [7]:
df.head()

,city_name,city_latitude,city_longitude,city_country_code,city_population,city_admin1_name,city_admin2_name,geometry
0,Vila,42.53176,1.56654,AD,1418,Encamp,,POINT (1.56654 42.53176)
1,Soldeu,42.57688,1.66769,AD,602,Canillo,,POINT (1.66769 42.57688)
2,Sispony,42.53368,1.51613,AD,833,La Massana,,POINT (1.51613 42.53368)
3,El Tarter,42.57952,1.65362,AD,1052,Canillo,,POINT (1.65362 42.57952)
4,Sant Julià de Lòria,42.46372,1.49129,AD,8022,Sant Julià de Loria,,POINT (1.49129 42.46372)

In [13]:
df[df["city_name"] == "Windsor"]

,city_name,city_latitude,city_longitude,city_country_code,city_population,city_admin1_name,city_admin2_name,geometry
6201,Windsor,-33.61309,150.81416,AU,1990,New South Wales,Hawkesbury,POINT (150.81416 -33.61309)
6202,Windsor,-37.85344,144.99241,AU,7273,Victoria,Stonnington,POINT (144.99241 -37.85344)
8144,Windsor,-27.43631,153.02882,AU,6983,Queensland,Brisbane,POINT (153.02882 -27.43631)
18521,Windsor,44.98345,-64.13204,CA,3864,Nova Scotia,Hants,POINT (-64.13204 44.98345)
18522,Windsor,45.56678,-71.99909,CA,5408,Quebec,Estrie,POINT (-71.99909 45.56678)
18523,Windsor,42.30008,-83.01654,CA,278013,Ontario,Essex County,POINT (-83.01654 42.30008)
84126,Windsor,51.48333,-0.60000,GB,33348,England,Royal Borough of Windsor and Maidenhead,POINT (-0.6 51.48333)
152066,Windsor,-46.39842,168.36009,NZ,3410,Southland,Invercargill City,POINT (168.36009 -46.39842)
193785,Windsor,39.44087,-88.59478,US,1162,Illinois,Shelby County,POINT (-88.59478 39.44087)
195873,Windsor,38.53224,-93.52215,US,2808,Missouri,Henry County,POINT (-93.52215 38.53224)
196715,Windsor,35.99849,-76.94606,US,3785,North Carolina,Bertie County,POINT (-76.94606 35.99849)
196716,Windsor,35.55294,-77.36108,US,2192,North Carolina,Pitt County,POINT (-77.36108 35.55294)
197732,Windsor,39.91621,-76.58441,US,1480,Pennsylvania,York County,POINT (-76.58441 39.91621)
199888,Windsor,36.80848,-76.74412,US,2671,Virginia,Isle of Wight County,POINT (-76.74412 36.80848)
200372,Windsor,41.85260,-72.64370,US,28778,Connecticut,Capitol Planning Region,POINT (-72.6437 41.8526)
202135,Windsor,42.51175,-73.05788,US,890,Massachusetts,Berkshire County,POINT (-73.05788 42.51175)
202471,Windsor,44.31063,-69.58060,US,2291,Maine,Kennebec County,POINT (-69.5806 44.31063)
205574,Windsor,42.07591,-75.64046,US,896,New York,Broome County,POINT (-75.64046 42.07591)
207535,Windsor,43.48035,-72.38481,US,2066,Vermont,Windsor County,POINT (-72.38481 43.48035)
208087,Windsor,43.21833,-89.34151,US,3573,Wisconsin,Dane County,POINT (-89.34151 43.21833)
209428,Windsor,38.54713,-122.81638,US,27464,California,Sonoma County,POINT (-122.81638 38.54713)
210386,Windsor,40.47748,-104.90136,US,21751,Colorado,Weld County,POINT (-104.90136 40.47748)

In [14]:
df[df["city_name"] == "Windsor"]

,city_name,city_latitude,city_longitude,city_country_code,city_population,city_admin1_name,city_admin2_name,geometry
6201,Windsor,-33.61309,150.81416,AU,1990,New South Wales,Hawkesbury,POINT (150.81416 -33.61309)
6202,Windsor,-37.85344,144.99241,AU,7273,Victoria,Stonnington,POINT (144.99241 -37.85344)
8144,Windsor,-27.43631,153.02882,AU,6983,Queensland,Brisbane,POINT (153.02882 -27.43631)
18521,Windsor,44.98345,-64.13204,CA,3864,Nova Scotia,Hants,POINT (-64.13204 44.98345)
18522,Windsor,45.56678,-71.99909,CA,5408,Quebec,Estrie,POINT (-71.99909 45.56678)
18523,Windsor,42.30008,-83.01654,CA,278013,Ontario,Essex County,POINT (-83.01654 42.30008)
84126,Windsor,51.48333,-0.60000,GB,33348,England,Royal Borough of Windsor and Maidenhead,POINT (-0.6 51.48333)
152066,Windsor,-46.39842,168.36009,NZ,3410,Southland,Invercargill City,POINT (168.36009 -46.39842)
193785,Windsor,39.44087,-88.59478,US,1162,Illinois,Shelby County,POINT (-88.59478 39.44087)
195873,Windsor,38.53224,-93.52215,US,2808,Missouri,Henry County,POINT (-93.52215 38.53224)
196715,Windsor,35.99849,-76.94606,US,3785,North Carolina,Bertie County,POINT (-76.94606 35.99849)
196716,Windsor,35.55294,-77.36108,US,2192,North Carolina,Pitt County,POINT (-77.36108 35.55294)
197732,Windsor,39.91621,-76.58441,US,1480,Pennsylvania,York County,POINT (-76.58441 39.91621)
199888,Windsor,36.80848,-76.74412,US,2671,Virginia,Isle of Wight County,POINT (-76.74412 36.80848)
200372,Windsor,41.85260,-72.64370,US,28778,Connecticut,Capitol Planning Region,POINT (-72.6437 41.8526)
202135,Windsor,42.51175,-73.05788,US,890,Massachusetts,Berkshire County,POINT (-73.05788 42.51175)
202471,Windsor,44.31063,-69.58060,US,2291,Maine,Kennebec County,POINT (-69.5806 44.31063)
205574,Windsor,42.07591,-75.64046,US,896,New York,Broome County,POINT (-75.64046 42.07591)
207535,Windsor,43.48035,-72.38481,US,2066,Vermont,Windsor County,POINT (-72.38481 43.48035)
208087,Windsor,43.21833,-89.34151,US,3573,Wisconsin,Dane County,POINT (-89.34151 43.21833)
209428,Windsor,38.54713,-122.81638,US,27464,California,Sonoma County,POINT (-122.81638 38.54713)
210386,Windsor,40.47748,-104.90136,US,21751,Colorado,Weld County,POINT (-104.90136 40.47748)

In [15]:
df[df["city_name"] == "New York City"]

,city_name,city_latitude,city_longitude,city_country_code,city_population,city_admin1_name,city_admin2_name,geometry
205121,New York City,40.71427,-74.00597,US,8804190,New York,,POINT (-74.00597 40.71427)

In [16]:
nyc = Point(-74.00597, 40.71427)
# 2. Create a GeoSeries for the point with its CRS
nyc_gs = gpd.GeoSeries([nyc], crs="EPSG:4326")

# 3. Choose a suitable projected CRS (UTM Zone 18N for NYC)
projected_crs = "EPSG:32618" # This CRS uses meters as its unit

# 4. Reproject the target point GeoSeries to the projected CRS
#    Then extract the single Point object from the GeoSeries
nyc_projected = nyc_gs.to_crs(projected_crs).iloc[0]
print(f"\nTarget point reprojected to CRS: {gpd.GeoSeries([nyc_projected], crs=projected_crs).crs}")


# 5. Create a buffer around the projected target point
#    The distance (15000) is now correctly interpreted as meters
distance_km = 10
distance_meters = distance_km * 1000
buffer_15km_projected = nyc_projected.buffer(distance_meters)
print(f"Buffer created with radius {distance_meters} meters in projected CRS.")

points_gdf = df.to_crs(crs="EPSG:32618")
points_within_15km_projected = points_gdf[points_gdf.geometry.intersects(buffer_15km_projected)]
print(len(points_within_15km_projected))
points_within_15km_projected

Target point reprojected to CRS: EPSG:32618
Buffer created with radius 10000 meters in projected CRS.
36

,city_name,city_latitude,city_longitude,city_country_code,city_population,city_admin1_name,city_admin2_name,geometry
204124,Guttenberg,40.79205,-74.00375,US,11665,New Jersey,Hudson County,POINT (584049.559 4516150.474)
204150,Hoboken,40.74399,-74.03236,US,53635,New Jersey,Hudson County,POINT (581694.656 4510788.431)
204158,Jersey City,40.72816,-74.07764,US,264290,New Jersey,Hudson County,POINT (577890.226 4508990.041)
204314,Secaucus,40.78955,-74.05653,US,19104,New Jersey,Hudson County,POINT (579599.649 4515823.706)
204353,Union City,40.77955,-74.02375,US,69156,New Jersey,Hudson County,POINT (582377.661 4514743.9)
204369,Weehawken,40.76955,-74.02042,US,14104,New Jersey,Hudson County,POINT (582671.053 4513636.957)
204374,West New York,40.78788,-74.01431,US,53366,New Jersey,Hudson County,POINT (583163.844 4515677.503)
204432,Astoria,40.77205,-73.93014,US,150165,New York,Queens County,POINT (590286.92 4514003.472)
204460,Battery Park City,40.71149,-74.01625,US,7422,New York,New York County,POINT (583095.21 4507195.832)
204502,Borough Park,40.63399,-73.99681,US,149248,New York,Kings County,POINT (584835.47 4498611.458)
204527,Brooklyn,40.65010,-73.94958,US,2736074,New York,Kings County,POINT (588808.219 4500446.375)
204528,Brooklyn Heights,40.69538,-73.99375,US,20256,New York,Kings County,POINT (585016.249 4505429.05)
204530,Brownsville,40.66094,-73.92014,US,74497,New York,Kings County,POINT (591282.504 4501679.826)
204535,Bushwick,40.69427,-73.91875,US,112620,New York,Kings County,POINT (591354.49 4505381.109)
204592,Chinatown,40.71649,-73.99625,US,90000,New York,New York County,POINT (584778.249 4507769.978)
204685,East Flatbush,40.65371,-73.93042,US,178464,New York,Kings County,POINT (590423.264 4500866.631)
204710,East Village,40.72927,-73.98736,US,62832,New York,New York County,POINT (585512.764 4509197.264)
204755,Flatbush,40.65205,-73.95903,US,93361,New York,Kings County,POINT (588006.689 4500653.336)
204828,Greenpoint,40.72371,-73.95097,US,34719,New York,Kings County,POINT (588593.156 4508616.144)
204868,Hell's Kitchen,40.76496,-73.99090,US,45884,New York,New York County,POINT (585168.273 4513155.669)
204936,Kensington,40.64621,-73.97069,US,39120,New York,Kings County,POINT (587028.489 4499993.46)
204998,Long Island City,40.74482,-73.94875,US,25595,New York,Queens County,POINT (588752.583 4510961.747)
205017,Manhattan,40.78343,-73.96625,US,1487536,New York,New York County,POINT (587224.611 4515230.204)
205029,Maspeth,40.72316,-73.91264,US,48325,New York,Queens County,POINT (591831.032 4508594.469)
205121,New York City,40.71427,-74.00597,US,8804190,New York,,POINT (583960.06 4507514.206)
205209,Park Slope,40.67010,-73.98597,US,65047,New York,Kings County,POINT (585705.956 4502630.375)
205294,Ridgewood,40.70010,-73.90569,US,69317,New York,Queens County,POINT (592449.885 4506041.939)
205432,Sunnyside,40.73982,-73.93542,US,49833,New York,Queens County,POINT (589884.73 4510420.275)
205456,Tribeca,40.71538,-74.00931,US,7811,New York,New York County,POINT (583676.555 4507634.236)
205565,Williamsburg,40.71427,-73.95347,US,33000,New York,Kings County,POINT (588394.509 4507565.72)
205585,Woodside,40.74538,-73.90541,US,41981,New York,Queens County,POINT (592410.886 4511068.639)
212001,Times Square,40.75636,-73.98644,US,17749,New York,New York County,POINT (585555.731 4512205.344)
212031,Gramercy Park,40.73750,-73.98611,US,27988,New York,New York County,POINT (585607.772 4510112.07)
212551,Financial District,40.70789,-74.00857,US,60976,New York,New York County,POINT (583748.443 4506803.503)
212552,Downtown Brooklyn,40.69371,-73.98596,US,7053,New York,Kings County,POINT (585676.562 4505251.236)
212553,Sunset Park,40.64548,-74.01241,US,126000,New York,Kings County,POINT (583501.905 4499871.98)

In [17]:
df2 = pd.read_csv('natural_earth_data/worldcities.csv')

In [18]:
len(df2)

48059

In [19]:
df2.head(20)

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6870,139.7495,Japan,JP,JPN,Tōkyō,primary,37785000.0,1392685764
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077
2,Delhi,Delhi,28.6100,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604
3,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133
4,Mumbai,Mumbai,19.0761,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1356226629
5,Manila,Manila,14.5958,120.9772,Philippines,PH,PHL,Manila,primary,24922000.0,1608618140
6,Shanghai,Shanghai,31.2286,121.4747,China,CN,CHN,Shanghai,admin,24073000.0,1156073548
7,São Paulo,Sao Paulo,-23.5504,-46.6339,Brazil,BR,BRA,São Paulo,admin,23086000.0,1076532519
8,Seoul,Seoul,37.5667,126.9833,"Korea, South",KR,KOR,Seoul,primary,23016000.0,1410836482
9,Mexico City,Mexico City,19.4333,-99.1333,Mexico,MX,MEX,Ciudad de México,primary,21804000.0,1484247881
10,Kolkāta,Kolkata,22.5675,88.3700,India,IN,IND,West Bengal,admin,21747000.0,1356060520
11,Cairo,Cairo,30.0444,31.2358,Egypt,EG,EGY,Al Qāhirah,primary,20296000.0,1818253931
12,Karachi,Karachi,24.8600,67.0100,Pakistan,PK,PAK,Sindh,admin,20249000.0,1586129469
13,Dhaka,Dhaka,23.7289,90.3944,Bangladesh,BD,BGD,Dhaka,primary,19134000.0,1050529279
14,New York,New York,40.6943,-73.9249,United States,US,USA,New York,NaN,18832416.0,1840034016
15,Beijing,Beijing,39.9067,116.3975,China,CN,CHN,Beijing,primary,18522000.0,1156228865
16,Bangkok,Bangkok,13.7525,100.4942,Thailand,TH,THA,Krung Thep Maha Nakhon,primary,18007000.0,1764068610
17,Shenzhen,Shenzhen,22.5415,114.0596,China,CN,CHN,Guangdong,minor,17619000.0,1156158707
18,Moscow,Moscow,55.7506,37.6175,Russia,RU,RUS,Moskva,primary,17332000.0,1643318494
19,Buenos Aires,Buenos Aires,-34.6036,-58.3814,Argentina,AR,ARG,"Buenos Aires, Ciudad Autónoma de",primary,16710000.0,1032717330

In [21]:
df2[df2["population"] < 500]

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
47594,Križevci,Krizevci,46.5683,16.1386,Slovenia,SI,SVN,Križevci,admin,499.0,1705138690
47595,Markovci,Markovci,46.3833,15.9500,Slovenia,SI,SVN,Markovci,admin,495.0,1705493301
47596,Staro Nagoričane,Staro Nagoricane,42.2000,21.8300,North Macedonia,MK,MKD,Staro Nagoričane,admin,493.0,1807782793
47597,Šmarješke Toplice,Smarjeske Toplice,45.8622,15.2214,Slovenia,SI,SVN,Šmarješke Toplice,admin,492.0,1705361649
47598,Karumba,Karumba,-17.4838,140.8397,Australia,AU,AUS,Queensland,NaN,487.0,1036926106
...,...,...,...,...,...,...,...,...,...,...,...
47803,Kostel,Kostel,45.5088,14.9100,Slovenia,SI,SVN,Kostel,admin,10.0,1705541759
47804,Kingoonya,Kingoonya,-30.9170,135.3147,Australia,AU,AUS,South Australia,NaN,4.0,1036942792
47826,Chuquicamata,Chuquicamata,-22.3169,-68.9301,Chile,CL,CHL,Antofagasta,NaN,0.0,1152468996
47969,Nordvik,Nordvik,73.9975,111.4633,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468
47970,Logashkino,Logashkino,70.8500,153.9167,Russia,RU,RUS,Sakha (Yakutiya),NaN,0.0,1643050775

In [61]:
df2[df2["city"] != df2["city_ascii"]]

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
7,São Paulo,Sao Paulo,-23.5504,-46.6339,Brazil,BR,BRA,São Paulo,admin,23086000.0,1076532519
10,Kolkāta,Kolkata,22.5675,88.3700,India,IN,IND,West Bengal,admin,21747000.0,1356060520
23,Ōsaka,Osaka,34.6939,135.5022,Japan,JP,JPN,Ōsaka,admin,15126000.0,1392419823
30,Xi’an,Xi'an,34.2611,108.9422,China,CN,CHN,Shaanxi,admin,12328000.0,1156244079
39,Hyderābād,Hyderabad,17.3617,78.4747,India,IN,IND,Telangāna,admin,10494000.0,1356871768
...,...,...,...,...,...,...,...,...,...,...,...
48045,Thành Phố Bà Rịa,Thanh Pho Ba Ria,10.4963,107.1685,Vietnam,VN,VNM,Bà Rịa-Vũng Tàu,admin,NaN,1704000020
48047,Đà Nẵng,Da Nang,16.0748,108.2240,Vietnam,VN,VNM,Đà Nẵng,admin,NaN,1704949870
48052,Satupa‘itea,Satupa`itea,-13.7659,-172.3269,Samoa,WS,WSM,Satupa‘itea,admin,NaN,1882940042
48053,‘Amrān,`Amran,15.6594,43.9439,Yemen,YE,YEM,‘Amrān,admin,NaN,1887433410
48054,Al Jabīn,Al Jabin,14.7040,43.5990,Yemen,YE,YEM,Raymah,admin,NaN,1887910100

In [52]:
# --- Configuration ---

# Output file
GEOJSON_OUTPUT_PATH = 'cities_merged.geojson'

# Parameters
RADIUS_METERS = 15000  # 15 km

def merge_city_data(gdf_cities, df_worldcities, output_path, radius):
    """
    Adds cities from a CSV to a GeoJSON, cleaning up redundant entries within a radius.

    Args:
        gdf_cities (str): geojson to work on.
        df_worldcities (str): csv to df.
        output_path (str): Path to save the merged GeoJSON file.
        radius (int): The radius in meters to search for redundant cities.
    """
    print("Step 2: Preparing GeoDataFrames...")
    # Create a GeoDataFrame from the world cities CSV
    geometry = [Point(xy) for xy in zip(df_worldcities.lng, df_worldcities.lat)]
    gdf_worldcities = gpd.GeoDataFrame(df_worldcities, geometry=geometry, crs="EPSG:4326")

    # To calculate distances in meters, we need to project our data to a suitable CRS.
    # EPSG:3857 (Web Mercator) is a common choice for this.
    gdf_cities_proj = gdf_cities.to_crs(epsg=3857)
    gdf_worldcities_proj = gdf_worldcities.to_crs(epsg=3857)

    # We'll keep track of original indices to drop and new rows to add
    indices_to_drop = set()
    new_city_rows = []

    print(f"Step 3: Processing {len(gdf_worldcities)} new cities...")
    # Iterate through each new city from the CSV to add it
    for idx, new_city in gdf_worldcities.iterrows():
        new_city_proj = gdf_worldcities_proj.loc[idx]

        # --- a) Find redundant cities to remove ---
        # Create a buffer (circle) around the new city
        buffer = new_city_proj.geometry.buffer(radius)

        # Find original cities that are within the buffer AND have the same country code
        mask_within_buffer = gdf_cities_proj.geometry.within(buffer)
        mask_same_country = gdf_cities_proj['city_country_code'] == new_city['iso2']
        
        redundant_indices = gdf_cities_proj[mask_within_buffer & mask_same_country].index
        indices_to_drop.update(redundant_indices)

        # --- b) Find nearest original city to inherit admin names ---
        # Use original CRS data for this, as we just need the closest point, not a specific distance
        all_original_points = gdf_cities.geometry.unary_union
        if all_original_points.is_empty:
            print(f"Warning: Original GeoDataFrame is empty. Cannot find a nearest neighbor for {new_city['city']}.")
            nearest_original_city = pd.Series({'city_admin1_name': None, 'city_admin2_name': None})
        else:
            _, nearest_geom = nearest_points(new_city.geometry, all_original_points)
            # Find the original city that corresponds to this nearest geometry
            nearest_original_city = gdf_cities[gdf_cities.geometry == nearest_geom].iloc[0]

        # --- c) Prepare the new row with the correct schema ---
        new_row = {
            'city_name': new_city['city_ascii'],
            'city_latitude': new_city['lat'],
            'city_longitude': new_city['lng'],
            'city_country_code': new_city['iso2'],
            'city_admin1_name': nearest_original_city['city_admin1_name'],
            'city_admin2_name': nearest_original_city['city_admin2_name'],
            'geometry': new_city.geometry
        }
        new_city_rows.append(new_row)

        if idx % 100 == 0:
            print(f"  Processed {idx + 1}/{len(gdf_worldcities)} new cities...")
            
    print("\nStep 4: Merging the data...")
    # Drop the redundant rows from the original dataframe
    print(f"  Found {len(indices_to_drop)} redundant cities to remove.")
    gdf_cities_pruned = gdf_cities.drop(index=list(indices_to_drop))
    print(f"  Original cities remaining: {len(gdf_cities_pruned)}")

    # Create a new GeoDataFrame for the cities we're adding
    gdf_new_cities = gpd.GeoDataFrame(new_city_rows, crs="EPSG:4326")
    print(f"  New cities to add: {len(gdf_new_cities)}")

    # Combine the pruned original data with the new data
    gdf_merged = pd.concat([gdf_cities_pruned, gdf_new_cities], ignore_index=True)

    print(f"\nStep 5: Saving merged file to {output_path}...")
    # Save the final result
    gdf_merged.to_file(output_path, driver='GeoJSON')
    print("--- Process Complete! ---")
    print(f"Final dataset contains {len(gdf_merged)} cities.")

    return gdf_merged


# The sample "geojson" in the prompt looks like a tab-separated file.
# The code includes a fallback to handle this format if geopandas fails to read it as a standard GeoJSON.
merge_city_data(
    gdf_cities=df,
    df_worldcities=df2,
    output_path=GEOJSON_OUTPUT_PATH,
    radius=RADIUS_METERS
)

Step 2: Preparing GeoDataFrames...
Step 3: Processing 48059 new cities...

C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union

  Processed 1/48059 new cities...

C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.

  Processed 101/48059 new cities...

C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union
C:\Users\larry\AppData\Local\Temp\ipykernel_28056\2367274919.py:51: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  all_original_points = gdf_cities.geometry.unary_union

KeyboardInterrupt:

In [ ]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

# This new helper function can be placed before your main function
def normalize_text(text):
    """
    Converts a string to its closest ASCII representation.
    Returns the original if input is not a string (e.g., None or NaN).
    """
    if isinstance(text, str):
        return unidecode(text)
    return text

def merge_and_update_cities(gdf_cities, df_worldcities, radius_meters=15000):
    """
    Merges and updates city data based on proximity.

    Instead of deleting, this function updates existing entries or adds new ones.
    - If an existing city (from gdf_cities) is within the radius of a new city
      (from df_worldcities), it gets a 'nearby_large_city' tag.
    - If a new city has no existing cities within its radius, it is added as a new row.

    Args:
        gdf_cities (gpd.GeoDataFrame): The original GeoDataFrame of cities.
        df_worldcities (pd.DataFrame): A DataFrame with the new, "cleaner" city data.
        radius_meters (int): The radius in meters to search for nearby cities.

    Returns:
        tuple: A tuple containing three GeoDataFrames:
               1. gdf_final_merged: The complete, merged, and updated dataset.
               2. gdf_updated_rows: A GDF of only the original rows that were updated.
               3. gdf_added_rows: A GDF of only the new rows that were added.
    """
    print("Step 1: Preparing data and initializing columns...")
    # Work on a copy to avoid modifying the original DataFrame passed to the function
    gdf_cities_updated = gdf_cities.copy()
    df_worldcities_cleaned = df_worldcities.copy()

    # --- ADD THIS BLOCK ---
    # Normalize text columns for consistent matching and clean output
    print("  Normalizing names to ASCII...")
    gdf_cities_updated['city_name'] = gdf_cities_updated['city_name'].apply(normalize_text)
    gdf_cities_updated['city_admin1_name'] = gdf_cities_updated['city_admin1_name'].apply(normalize_text)
    
    df_worldcities_cleaned['city_ascii'] = df_worldcities_cleaned['city_ascii'].apply(normalize_text)
    df_worldcities_cleaned['admin_name'] = df_worldcities_cleaned['admin_name'].apply(normalize_text)
    # --- END OF ADDED BLOCK ---
    
    # Add the new column and initialize it with a null value (pandas' NA is preferred)
    gdf_cities_updated['nearby_large_city'] = pd.NA

    # Create a GeoDataFrame from the world cities DataFrame
    geometry = [Point(xy) for xy in zip(df_worldcities_cleaned.lng, df_worldcities_cleaned.lat)]
    gdf_worldcities = gpd.GeoDataFrame(df_worldcities_cleaned, geometry=geometry, crs="EPSG:4326")

    print("Step 2: Projecting data for accurate distance calculation...")
    # Use a projected CRS (like Web Mercator) to work with meters
    gdf_cities_proj = gdf_cities_updated.to_crs(epsg=3857)
    gdf_worldcities_proj = gdf_worldcities.to_crs(epsg=3857)

    # Keep track of which original rows were updated and which new rows to add
    updated_indices = set()
    new_city_rows = []

    print(f"Step 3: Processing {len(gdf_worldcities)} new cities...")
    # Iterate through each "clean" city from the CSV
    for idx, new_city in gdf_worldcities.iterrows():
        new_city_proj = gdf_worldcities_proj.loc[idx]

        # Create a buffer (circle) around the new city to define the search area
        buffer = new_city_proj.geometry.buffer(radius_meters)

        # Find original cities within the buffer and with the same country code
        mask_within_buffer = gdf_cities_proj.geometry.within(buffer)
        mask_same_country = gdf_cities_proj['city_country_code'] == new_city['iso2']
        
        nearby_original_indices = gdf_cities_proj[mask_within_buffer & mask_same_country].index

        if not nearby_original_indices.empty:
            # --- LOGIC A: FOUND NEARBY CITY ---
            # Update the 'nearby_large_city' column for the found cities
            gdf_cities_updated.loc[nearby_original_indices, 'nearby_large_city'] = new_city['city_ascii']
            # Record the indices of the rows we modified
            updated_indices.update(nearby_original_indices)
        else:
            # --- LOGIC B: NO NEARBY CITY FOUND ---
            # Add the new city from the CSV as a new row to our dataset
            new_row = {
                'city_name': new_city['city_ascii'],
                'city_latitude': new_city['lat'],
                'city_longitude': new_city['lng'],
                'city_country_code': new_city['iso2'],
                'city_admin1_name': new_city['admin_name'], # Map admin_name to city_admin1_name
                'city_admin2_name': None, # No source for admin2, so set to None
                'geometry': new_city.geometry,
                'nearby_large_city': pd.NA # This city is the 'large city', not near one
            }
            new_city_rows.append(new_row)

        if (idx + 1) % 100 == 0:
            print(f"  Processed {idx + 1}/{len(gdf_worldcities)} new cities...")

    print("\nStep 4: Assembling final GeoDataFrames...")
    # Create a GeoDataFrame for the newly added cities
    gdf_added_rows = gpd.GeoDataFrame(new_city_rows, crs="EPSG:4326")
    print(f"  Found {len(updated_indices)} original cities to update.")
    print(f"  Found {len(gdf_added_rows)} new cities to add.")

    # Get a dataframe of only the rows that were modified
    gdf_updated_rows = gdf_cities_updated.loc[list(updated_indices)].copy()

    # Combine the (now updated) original data with the new city rows
    gdf_final_merged = pd.concat([gdf_cities_updated, gdf_added_rows], ignore_index=True)

    print("\n--- Process Complete! ---")
    print(f"Final dataset contains {len(gdf_final_merged)} cities.")
    
    return gdf_final_merged, gdf_updated_rows, gdf_added_rows



# --- Call the Function ---
final_gdf, updated_gdf, added_gdf = merge_and_update_cities(
    gdf_cities=df,
    df_worldcities=df2,
    radius_meters=15000
)

# --- Handle and Inspect the Outputs ---
print("\n\n--- OUTPUTS ---")

print("\n1. Final Merged GeoDataFrame (first 5 rows):")
print(final_gdf.head())

print("\n2. Rows from Original GDF that were UPDATED:")
print(updated_gdf)

print("\n3. Rows that were NEWLY ADDED:")
print(added_gdf)

# --- Save the results to files ---
print("\nSaving files...")
final_gdf.to_file("cities_final_merged.geojson", driver='GeoJSON')
updated_gdf.to_csv("cities_updated_rows.csv", index=False)
added_gdf.to_csv("cities_added_rows.csv", index=False)
print("Files saved successfully.")

In [ ]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from unidecode import unidecode

def normalize_text(text):
    """
    Converts a string to its closest ASCII representation.
    """
    if isinstance(text, str):
        return unidecode(text)
    return text

def merge_and_update_cities(gdf_cities, df_worldcities, radius_meters=15000):
    """
    Merges and updates city data based on proximity, ensuring the closest city is chosen.

    - Uses sjoin_nearest to guarantee the closest "large city" is assigned.
    - If an existing city is within the radius of a new city, it gets a 'nearby_large_city' tag.
    - If a new city has no existing cities within its radius, it is added as a new row.
    """
    print("Step 1: Preparing data and normalizing names...")
    gdf_cities_normalized = gdf_cities.copy()
    df_worldcities_cleaned = df_worldcities.copy()

    # Normalize text columns for consistent matching
    gdf_cities_normalized['city_name'] = gdf_cities_normalized['city_name'].apply(normalize_text)
    gdf_cities_normalized['city_admin1_name'] = gdf_cities_normalized['city_admin1_name'].apply(normalize_text)
    
    df_worldcities_cleaned['city_ascii'] = df_worldcities_cleaned['city_ascii'].apply(normalize_text)
    df_worldcities_cleaned['admin_name'] = df_worldcities_cleaned['admin_name'].apply(normalize_text)

    # Create a GeoDataFrame from the world cities DataFrame
    geometry = [Point(xy) for xy in zip(df_worldcities_cleaned.lng, df_worldcities_cleaned.lat)]
    gdf_worldcities = gpd.GeoDataFrame(df_worldcities_cleaned, geometry=geometry, crs="EPSG:4326")

    print("Step 2: Projecting data for accurate distance calculation...")
    gdf_cities_proj = gdf_cities_normalized.to_crs(epsg=3857)
    gdf_worldcities_proj = gdf_worldcities.to_crs(epsg=3857)

    # --- REVISED LOGIC: Use sjoin_nearest to find the closest match ---
    print("Step 3: Finding closest large city for each original city...")
    
    # This single operation replaces the entire for-loop.
    # It finds the nearest city in gdf_worldcities_proj for each city in gdf_cities_proj,
    # but only if it's within radius_meters.
    # 'how=left' ensures we keep all original cities.
    gdf_cities_updated = gpd.sjoin_nearest(
        gdf_cities_proj, 
        gdf_worldcities_proj, 
        max_distance=radius_meters, 
        how='left',
        rsuffix='large' # Suffix for columns from the right GeoDataFrame
    )
    
    # Rename the joined column to 'nearby_large_city'
    # The name is 'city_ascii_large' because of the 'rsuffix'
    gdf_cities_updated.rename(columns={'city_ascii': 'nearby_large_city'}, inplace=True)
    
    # Select only the columns we want to keep, cleaning up extra columns from the join
    # (like index_large, lat_large, country_large, etc.)
    final_cols = list(gdf_cities_normalized.columns) + ['nearby_large_city']
    gdf_cities_updated = gdf_cities_updated[final_cols]

    # Convert back to the original CRS
    gdf_cities_updated = gdf_cities_updated.to_crs("EPSG:4326")


    print("\nStep 4: Identifying new cities to add...")
    # Find which large cities were successfully matched to an original city
    matched_large_city_indices = gdf_cities_updated[gdf_cities_updated['nearby_large_city'].notna()].index

    # To find which worldcities were used, we need to go back to the join result
    join_result = gpd.sjoin_nearest(gdf_cities_proj, gdf_worldcities_proj, max_distance=radius_meters, how='inner')
    used_worldcities_indices = join_result['index_right'].unique()

    # The cities to add are those in gdf_worldcities whose indices were NOT used in the join
    new_cities_to_add_df = gdf_worldcities[~gdf_worldcities.index.isin(used_worldcities_indices)]
    print(f"  Found {len(new_cities_to_add_df)} new cities to add.")

    new_city_rows = []
    for _, new_city in new_cities_to_add_df.iterrows():
        new_row = {
            'city_name': new_city['city_ascii'],
            'city_latitude': new_city['lat'],
            'city_longitude': new_city['lng'],
            'city_country_code': new_city['iso2'],
            'city_admin1_name': new_city['admin_name'],
            'city_admin2_name': None,
            'geometry': new_city.geometry,
            'nearby_large_city': pd.NA 
        }
        new_city_rows.append(new_row)

    print("\nStep 5: Assembling final GeoDataFrames...")
    gdf_added_rows = gpd.GeoDataFrame(new_city_rows, crs="EPSG:4326")

    # Get a dataframe of only the rows that were modified
    gdf_updated_rows = gdf_cities_updated[gdf_cities_updated['nearby_large_city'].notna()].copy()
    print(f"  Found {len(gdf_updated_rows)} original cities to update.")

    # Combine the (now updated) original data with the new city rows
    gdf_final_merged = pd.concat([gdf_cities_updated, gdf_added_rows], ignore_index=True)

    print("\n--- Process Complete! ---")
    print(f"Final dataset contains {len(gdf_final_merged)} cities.")
    
    return gdf_final_merged, gdf_updated_rows, gdf_added_rows

# --- Example Usage (assuming df and df2 are pre-loaded) ---
final_gdf, updated_gdf, added_gdf = merge_and_update_cities(
    gdf_cities=df,
    df_worldcities=df2,
    radius_meters=15000
)

Step 1: Preparing data and normalizing names...
Step 2: Projecting data for accurate distance calculation...
Step 3: Finding closest large city for each original city...

Step 4: Identifying new cities to add...
  Found 10337 new cities to add.

Step 5: Assembling final GeoDataFrames...
  Found 118943 original cities to update.

--- Process Complete! ---
Final dataset contains 226556 cities.

In [63]:
added_gdf

,city_name,city_latitude,city_longitude,city_country_code,city_admin1_name,city_admin2_name,geometry,nearby_large_city
0,Manila,14.5958,120.9772,PH,Manila,None,POINT (120.9772 14.5958),<NA>
1,Nangandao,35.3036,113.9268,CN,Henan,None,POINT (113.9268 35.3036),<NA>
2,Nanchong,30.8372,106.1106,CN,Sichuan,None,POINT (106.1106 30.8372),<NA>
3,Abidjan,5.3364,-4.0267,CI,Abidjan,None,POINT (-4.0267 5.3364),<NA>
4,Belahi,26.4000,86.2500,IN,Bihar,None,POINT (86.25 26.4),<NA>
...,...,...,...,...,...,...,...,...
10332,Budaka,1.0173,33.9556,UG,Budaka,None,POINT (33.9556 1.0173),<NA>
10333,Kibaale,0.7958,31.0792,UG,Kibaale,None,POINT (31.0792 0.7958),<NA>
10334,Leju,3.1859,31.0610,UG,Arua,None,POINT (31.061 3.1859),<NA>
10335,Nabilatuk,2.0525,34.5734,UG,Nabilatuk,None,POINT (34.5734 2.0525),<NA>
10336,Gqeberha,-33.9681,25.5981,ZA,Eastern Cape,None,POINT (25.5981 -33.9681),<NA>

In [64]:
df[df["city_name"] == "Manila"]

,city_name,city_latitude,city_longitude,city_country_code,city_admin1_name,city_admin2_name,geometry
138764,Manila,25.69100,-103.53966,MX,Durango,Gómez Palacio,POINT (-103.53966 25.691)
157475,Manila,14.60420,120.98220,PH,Metro Manila,Capital District,POINT (120.9822 14.6042)
192052,Manila,35.88007,-90.16704,US,Arkansas,Mississippi County,POINT (-90.16704 35.88007)
210300,Manila,40.85179,-124.16229,US,California,Humboldt County,POINT (-124.16229 40.85179)
211147,Manila,40.98801,-109.72265,US,Utah,Daggett County,POINT (-109.72265 40.98801)

In [70]:
final_gdf[final_gdf["city_name"] == "Abidjan"]

,city_name,city_latitude,city_longitude,city_country_code,city_admin1_name,city_admin2_name,geometry,nearby_large_city
24765,Abidjan,5.35444,-4.00167,CI,Abidjan Autonomous District,,POINT (-4.00167 5.35444),Cocody
216222,Abidjan,5.33640,-4.02670,CI,Abidjan,None,POINT (-4.0267 5.3364),NaN